const symbols = [
  // Stocks
  { "icon": "🌐", "name": "NVDA", "description": "NVIDIA Corporation", "market": "NasdaqGS", "type": "stock" },
  { "icon": "🌐", "name": "TSLA", "description": "Tesla, Inc.", "market": "NasdaqGS", "type": "stock" },
  { "icon": "🌐", "name": "MSFT", "description": "Microsoft Corporation", "market": "NasdaqGS", "type": "stock" },
  { "icon": "🌐", "name": "AAPL", "description": "Apple Inc.", "market": "NasdaqGS", "type": "stock" },
  { "icon": "🌐", "name": "GOOGL", "description": "Alphabet Inc.", "market": "NasdaqGS", "type": "stock" },
  { "icon": "🌐", "name": "INTC", "description": "Intel Corporation", "market": "NasdaqGS", "type": "stock" },
  { "icon": "🌐", "name": "RELIANCE.NS", "description": "RELIANCE INDUSTRIES LTD", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "WIPRO.NS", "description": "WIPRO LTD", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NFLX", "description": "Netflix, Inc.", "market": "NasdaqGS", "type": "stock" },
  { "icon": "🌐", "name": "COIN", "description": "Coinbase Global, Inc.", "market": "NasdaqGS", "type": "stock" },
  { "icon": "🌐", "name": "BABA", "description": "Alibaba Group Holding Limited", "market": "NYSE", "type": "stock" },
  { "icon": "🌐", "name": "AMZN", "description": "Amazon.com, Inc.", "market": "NasdaqGS", "type": "stock" },
  { "icon": "🌐", "name": "META", "description": "Meta Platforms, Inc.", "market": "NasdaqGS", "type": "stock" },
  { "icon": "🌐", "name": "DIS", "description": "The Walt Disney Company", "market": "NYSE", "type": "stock" },
  { "icon": "🌐", "name": "VZ", "description": "Verizon Communications Inc.", "market": "NYSE", "type": "stock" },
  { "icon": "🌐", "name": "TRENT.NS", "description": "Trent Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BHARTIARTL.NS", "description": "Bharti Airtel Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NTPC.NS", "description": "NTPC Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MARUTI.NS", "description": "Maruti Suzuki India Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BAJAJ-AUTO.NS", "description": "Bajaj Auto Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HDFCLIFE.NS", "description": "HDFC Life Insurance Company Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TCS.NS", "description": "Tata Consultancy Services Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BAJFINANCE.NS", "description": "Bajaj Finance Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ULTRACEMCO.NS", "description": "UltraTech Cement Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TATASTEEL.NS", "description": "Tata Steel Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HEROMOTOCO.NS", "description": "Hero MotoCorp Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CIPLA.NS", "description": "Cipla Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KOTAKBANK.NS", "description": "Kotak Mahindra Bank Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BAJAJFINSV.NS", "description": "Bajaj Finserv Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SHRIRAMFIN.NS", "description": "Shriram Finance Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ADANIENT.NS", "description": "Adani Enterprises Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INDUSINDBK.NS", "description": "IndusInd Bank Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ITC.NS", "description": "ITC Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LT.NS", "description": "Larsen & Toubro Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "COALINDIA.NS", "description": "Coal India Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TATACONSUM.NS", "description": "Tata Consumer Products Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BRITANNIA.NS", "description": "Britannia Industries Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NESTLEIND.NS", "description": "Nestlé India Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "APOLLOHOSP.NS", "description": "Apollo Hospitals Enterprise Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HINDALCO.NS", "description": "Hindalco Industries Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TITAN.NS", "description": "Titan Company Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ONGC.NS", "description": "Oil and Natural Gas Corporation Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HDFCBANK.NS", "description": "HDFC Bank Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HINDUNILVR.NS", "description": "Hindustan Unilever Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TATAMOTORS.NS", "description": "Tata Motors Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AXISBANK.NS", "description": "Axis Bank Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ICICIBANK.NS", "description": "ICICI Bank Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TATAPOWER.NS", "description": "Tata Power Company Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HINDPETRO.NS", "description": "Hindustan Petroleum Corporation Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ADANIGREEN.NS", "description": "Adani Green Energy Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ADANIPORTS.NS", "description": "Adani Ports and Special Economic Zone Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HDFC.NS", "description": "Housing Development Finance Corporation Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HDFCAMC.NS", "description": "HDFC Asset Management Company Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HINDZINC.NS", "description": "Hindustan Zinc Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "UPL.NS", "description": "UPL Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MARICO.NS", "description": "Marico Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ADANITRANS.NS", "description": "Adani Transmission Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TATAMETALI.NS", "description": "Tata Metaliks Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MINDTREE.NS", "description": "LTIMindtree", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TATAMTRDVR.NS", "description": "Tata Motors Limited DVR", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HCLTECH.NS", "description": "HCL Technologies Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ZOMATO.NS", "description": "Zomato Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INFY.NS", "description": "Infosys", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SBIN.NS", "description": "State Bank of India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LTI.NS", "description": "Larsen & Toubro Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IOC.NS", "description": "Indian Oil Corporation Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BPCL.NS", "description": "Bharat Petroleum Corporation Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SBILIFE.NS", "description": "SBI Life Insurance Company Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PNB.NS", "description": "Punjab National Bank", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BANKBARODA.NS", "description": "Bank of Baroda", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "M&M.NS", "description": "Mahindra & Mahindra Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IDFCFIRSTB.NS", "description": "IDFC First Bank Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CANBK.NS", "description": "Canara Bank", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "FEDERALBNK.NS", "description": "The Federal Bank Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BANDHANBNK.NS", "description": "Bandhan Bank Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "YESBANK.NS", "description": "Yes Bank Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RBLBANK.NS", "description": "RBL Bank Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IDBI.NS", "description": "IDBI Bank Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "UNIONBANK.NS", "description": "Union Bank of India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INDIANB.NS", "description": "Indian Bank", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IOB.NS", "description": "Indian Overseas Bank", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "UCOBANK.NS", "description": "UCO Bank", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CENTRALBK.NS", "description": "Central Bank of India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ASIANPAINT.NS", "description": "Asian Paints Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SUNPHARMA.NS", "description": "Sun Pharmaceutical Industries Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NESTLEIND.NS", "description": "Nestlé India Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DRREDDY.NS", "description": "Dr. Reddy's Laboratories Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "POWERGRID.NS", "description": "Power Grid Corporation of India Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GRASIM.NS", "description": "Grasim Industries Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TECHM.NS", "description": "Tech Mahindra Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "COALINDIA.NS", "description": "Coal India Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DIVISLAB.NS", "description": "Divi's Laboratories Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BRITANNIA.NS", "description": "Britannia Industries Limited", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ADANITRANS.NS", "description": "Adani Transmission Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ADANIGAS.NS", "description": "Adani Total Gas Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AWL.NS", "description": "Adani Wilmar Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ABCAPITAL.NS", "description": "Aditya Birla Capital Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ABFRL.NS", "description": "Aditya Birla Fashion and Retail Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ACC.NS", "description": "ACC Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GAIL.NS", "description": "GAIL (India) Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GODREJCP.NS", "description": "Godrej Consumer Products Ltd.", "market": "NSE", "type": "stock", },
  { "icon": "🌐", "name": "HAVELLS.NS", "description": "Havells India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INDIGO.NS", "description": "InterGlobe Aviation Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JSWSTEEL.NS", "description": "JSW Steel Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MARICO.NS", "description": "Marico Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MUTHOOTFIN.NS", "description": "Muthoot Finance Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PAGEIND.NS", "description": "Page Industries Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PEL.NS", "description": "Piramal Enterprises Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PETRONET.NS", "description": "Petronet LNG Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PIDILITIND.NS", "description": "Pidilite Industries Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PIIND.NS", "description": "PI Industries Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PGHH.NS", "description": "Procter & Gamble Hygiene and Health Care Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "COLPAL.NS", "description": "Colgate-Palmolive (India) Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LLOYDMET.NS", "description": "Lloyds Metals and Energy Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LICI.NS", "description": "Life Insurance Corporation of India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GILLETTE.NS", "description": "Gillette India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IRCTC.NS", "description": "Indian Railway Catering and Tourism Corporation Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HYUNDAI.NS", "description": "Hyundai Motor India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GLAXO.NS", "description": "GlaxoSmithKline Pharmaceuticals Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CGPOWER.NS", "description": "CG Power and Industrial Solutions Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ABBOTINDIA.NS", "description": "Abbott India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MAZDOCK.NS", "description": "Mazagon Dock Shipbuilders Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "WAAREE.NS", "description": "Waaree Energies Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MARICO.NS", "description": "Marico Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TATAELXSI.NS", "description": "Tata Elxsi Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CDSL.NS", "description": "Central Depository Services (India) Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "OFSS.NS", "description": "Oracle Financial Services Software Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AUTHUM.NS", "description": "Authum Investment & Infrastructure Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HAL.NS", "description": "Hindustan Aeronautics Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ABB.NS", "description": "A B B", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KPITTECH.NS", "description": "KPIT Technologies Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CRISIL.NS", "description": "CRISIL Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NIPPONIND.NS", "description": "Nippon Life India Asset Management Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CUMMINSIND.NS", "description": "Cummins India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BEL.NS", "description": "Bharat Electronics Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LTTS.NS", "description": "L&T Technology Services Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "3MINDIA.NS", "description": "3M India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SOLARINDS.NS", "description": "Solar Industries India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ADANIPOWER.NS", "description": "Adani Power Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "EMAMI.NS", "description": "Emami Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AJANTPHARM.NS", "description": "Ajanta Pharma Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "POLYCAB.NS", "description": "Polycab India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LTIM.NS", "description": "LTIMindtree Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "EICHERMOT.NS", "description": "Eicher Motors Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NMDC.NS", "description": "NMDC Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INVENTURUS.NS", "description": "Inventurus Knowledge Solutions Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HEXAWARE.NS", "description": "Hexaware Technologies Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PERSISTENT.NS", "description": "Persistent Systems Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DIXON.NS", "description": "Dixon Technologies (India) Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IGL.NS", "description": "Indraprastha Gas Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "COFORGE.NS", "description": "Coforge Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SUPREMEIND.NS", "description": "Supreme Industries Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TATATECH.NS", "description": "Tata Technologies Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "UNITEDSPIR.NS", "description": "United Spirits Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BERGEPAINT.NS", "description": "Berger Paints India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KEI.NS", "description": "KEI Industries Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NH.NS", "description": "Narayana Hrudayalaya Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TUBEINVEST.NS", "description": "Tube Investments of India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SUNTV.NS", "description": "Sun TV Network Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "COROMANDEL.NS", "description": "Coromandel International Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SCHAEFFLER.NS", "description": "Schaeffler India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BLUESTARCO.NS", "description": "Blue Star Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PREMIER.NS", "description": "Premier Energies Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "APLAPOLLO.NS", "description": "APL Apollo Tubes Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SUZLON.NS", "description": "Suzlon Energy Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "VBL.NS", "description": "Varun Beverages Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MANKIND.NS", "description": "Mankind Pharma Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JBCHEPHARM.NS", "description": "J B Chemicals & Pharmaceuticals Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BDL.NS", "description": "Bharat Dynamics Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SONACOMS.NS", "description": "Sona BLW Precision Forgings Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MPHASIS.NS", "description": "Mphasis Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SIEMENS.NS", "description": "Siemens Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ASTRAL.NS", "description": "Astral Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TORNTPHARM.NS", "description": "Torrent Pharmaceuticals Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GEVERNOVA.NS", "description": "GE Vernova T&D India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AIAENG.NS", "description": "AIA Engineering Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ICICIGI.NS", "description": "ICICI Lombard General Insurance Co. Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ZYDUSLIFE.NS", "description": "Zydus Lifesciences Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DABUR.NS", "description": "Dabur India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JSL.NS", "description": "Jindal Stainless Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GODFRYPHLP.NS", "description": "Godfrey Phillips India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INDUSTOWER.NS", "description": "Indus Towers Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DEEPAKNTR.NS", "description": "Deepak Nitrite Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "COCHINSHIP.NS", "description": "Cochin Shipyard Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ATGL.NS", "description": "Adani Total Gas Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IOCL.NS", "description": "Indian Oil Corporation Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "VEDL.NS", "description": "Vedanta Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ZFCOMMERCIAL.NS", "description": "ZF Commercial Vehicles Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SUMITOMO.NS", "description": "Sumitomo Chemical India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MOTILOSWAL.NS", "description": "Motilal Oswal Financial Services Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KPRMILL.NS", "description": "KPR Mill Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BOSCHLTD.NS", "description": "Bosch Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GUJGASLTD.NS", "description": "Gujarat Gas Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CHAMBLFERT.NS", "description": "Chambal Fertilisers & Chemicals Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BSE.NS", "description": "BSE Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "UNOMINDA.NS", "description": "UNO Minda Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HONAUTO.NS", "description": "Honeywell Automation India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ICICISEC.NS", "description": "ICICI Securities Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ALKEM.NS", "description": "Alkem Laboratories Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "METROBRAND.NS", "description": "Metro Brands Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DMART.NS", "description": "Avenue Supermarts Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GLOBALHEALTH.NS", "description": "Global Health Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SUVENPHAR.NS", "description": "Suven Pharmaceuticals Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PGEL.NS", "description": "PG Electroplast Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RVNL.NS", "description": "Rail Vikas Nigam Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HITACHI.NS", "description": "Hitachi Energy India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "OIL.NS", "description": "Oil India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BALKRISIND.NS", "description": "Balkrishna Industries Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TATACOMM.NS", "description": "Tata Communications Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NATIONALUM.NS", "description": "National Aluminium Company Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "FACT.NS", "description": "Fertilisers and Chemicals Travancore Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "THERMAX.NS", "description": "Thermax Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KIMS.NS", "description": "Krishna Institute of Medical Sciences Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ENDURANCE.NS", "description": "Endurance Technologies Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "APOLLOTYRE.NS", "description": "Apollo Tyres Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JSWINFRA.NS", "description": "JSW Infrastructure Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MRF.NS", "description": "MRF Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ESCORTS.NS", "description": "Escorts Kubota Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MAXHEALTH.NS", "description": "Max Healthcare Institute Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JKCEMENT.NS", "description": "JK Cement Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GICRE.NS", "description": "General Insurance Corporation of India.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LUPIN.NS", "description": "Lupin Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "OBEROIRLTY.NS", "description": "Oberoi Realty Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INDHOTEL.NS", "description": "Indian Hotels Company Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ASHOKLEY.NS", "description": "Ashok Leyland Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PRESTIGE.NS", "description": "Prestige Estates Projects Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TORNTPOWER.NS", "description": "Torrent Power Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SHREECEM.NS", "description": "Shree Cement Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AEGISLOG.NS", "description": "Aegis Logistics Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SYNGENE.NS", "description": "Syngene International Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TVSMOTOR.NS", "description": "TVS Motor Company Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KAYNES.NS", "description": "Kaynes Technology India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "360ONE.NS", "description": "360 ONE WAM Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AUROPHARMA.NS", "description": "Aurobindo Pharma Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KALYAN.NS", "description": "Kalyan Jewellers India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BHARTIHEXA.NS", "description": "Bharti Hexacom Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CONCOR.NS", "description": "Container Corporation of India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SAMVARDHAN.NS", "description": "Samvardhana Motherson International Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GLAND.NS", "description": "Gland Pharma Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "UBL.NS", "description": "United Breweries Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RADICO.NS", "description": "Radico Khaitan Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JINDALSTEL.NS", "description": "Jindal Steel & Power Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MUTHOOTFIN.NS", "description": "Muthoot Finance Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BAJAJHLDNG.NS", "description": "Bajaj Holdings & Investment Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BHARATFORG.NS", "description": "Bharat Forge Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AMBUJACEM.NS", "description": "Ambuja Cements Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IPCALAB.NS", "description": "Ipca Laboratories Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SRF.NS", "description": "SRF Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SBICARD.NS", "description": "SBI Cards and Payment Services Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PHOENIXLTD.NS", "description": "The Phoenix Mills Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GLENMARK.NS", "description": "Glenmark Pharmaceuticals Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SHRIRAMFIN.NS", "description": "Shriram Finance Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JUBLFOOD.NS", "description": "Jubilant FoodWorks Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PATANJALI.NS", "description": "Patanjali Foods Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LODHA.NS", "description": "Macrotech Developers Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "POONAWALLA.NS", "description": "Poonawalla Fincorp Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CHOLAFIN.NS", "description": "Cholamandalam Investment and Finance Company Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CHOLAHLDG.NS", "description": "Cholamandalam Financial Holdings Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "FORTIS.NS", "description": "Fortis Healthcare Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "EXIDEIND.NS", "description": "Exide Industries Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RECLTD.NS", "description": "REC Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PFC.NS", "description": "Power Finance Corporation Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MFSL.NS", "description": "Max Financial Services Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GUJFLUORO.NS", "description": "Gujarat Fluorochemicals Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BAJAJHSG.NS", "description": "Bajaj Housing Finance Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IRFC.NS", "description": "Indian Renewable Energy Development Agency Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HUDCO.NS", "description": "Housing and Urban Development Corporation Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SUNDARMFIN.NS", "description": "Sundaram Finance Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ADANIESL.NS", "description": "Adani Energy Solutions Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IRB.NS", "description": "IRB Infrastructure Developers Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LICHSGFIN.NS", "description": "LIC Housing Finance Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ICICIPRULI.NS", "description": "ICICI Prudential Life Insurance Company Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "M&MFIN.NS", "description": "Mahindra & Mahindra Financial Services Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JSWENERGY.NS", "description": "JSW Energy Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "VOLTAS.NS", "description": "Voltas Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LTF.NS", "description": "L&T Finance Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SAIL.NS", "description": "Steel Authority of India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JSWHLDG.NS", "description": "JSW Holdings", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NIACL.NS", "description": "New India Assurance", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IDEA.NS", "description": "Vodafone Idea", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PAYTM.NS", "description": "One 97 (Paytm)", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SWIGGY.NS", "description": "Swiggy", "market": "Unlisted", "type": "stock" },
  { "icon": "🌐", "name": "ITCHOTEL.NS", "description": "ITC Hotels", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AUBANK.NS", "description": "AU Small Finance Bank Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NHPC.NS", "description": "NHPC Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NTPCGREEN.NS", "description": "NTPC Green Energy Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ALTIUSTEL.NS", "description": "Altius Telecom Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MCX.NS", "description": "Multi Commodity Exchange of India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NYKAA.NS", "description": "FSN E-Commerce Ventures Ltd. (Nykaa)", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DALMIABHARAT.NS", "description": "Dalmia Bharat Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GODIGIT.NS", "description": "Go Digit General Insurance Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LAURUSLABS.NS", "description": "Laurus Labs Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NLCINDIA.NS", "description": "NLC India Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GMRAIRPORT.NS", "description": "GMR Airports Infrastructure Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BIOCON.NS", "description": "Biocon Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DLF.NS", "description": "DLF Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GODREJPROP.NS", "description": "Godrej Properties Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BANKINDIA.NS", "description": "Bank of India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PSB.NS", "description": "Punjab & Sind Bank", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GODREJIND.NS", "description": "Godrej Industries Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PIRAMALPH.NS", "description": "Piramal Pharma Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "EMBASSY.NS", "description": "Embassy Office Parks REIT", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MAHABANK.NS", "description": "Bank of Maharashtra", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CENTRALBANK.NS", "description": "Central Bank of India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SJVN.NS", "description": "SJVN Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INFOEDGE.NS", "description": "Info Edge (India) Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BHEL.NS", "description": "Bharat Heavy Electricals Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NHAI.NS", "description": "National Highways Authority of India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "VODAFONEIDEA.NS", "description": "Vodafone Idea Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JIOFIN.NS", "description": "Jio Financial Services", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AMBER.NS", "description": "Amber Enterprises", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ASTERDM.NS", "description": "Aster DM Healthcare", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JYOTICNC.NS", "description": "Jyoti CNC Automation", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "FSL.NS", "description": "Firstsource Solutions", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ITI.NS", "description": "ITI Ltd", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BRIGADE.NS", "description": "Brigade Enterprises", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SHYAMMETL.NS", "description": "Shyam Metalics", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MRPL.NS", "description": "Mangalore Refinery & Petrochemicals", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "OLA.NS", "description": "Ola Electric", "market": "Private", "type": "stock" },
  { "icon": "🌐", "name": "WOCKPHARMA.NS", "description": "Wockhardt", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MOTHERSUMI.NS", "description": "Motherson Wiring", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PNBHOUSING.NS", "description": "PNB Housing Finance", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "WELCORP.NS", "description": "Welspun Corp", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CROMPTON.NS", "description": "Crompton Greaves Consumer Electricals", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "POLYMED.NS", "description": "Poly Medicure", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AFFLE.NS", "description": "Affle India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PTCIL.NS", "description": "PTC Industries", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PEL.NS", "description": "Piramal Enterprises", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "APARINDS.NS", "description": "Apar Industries", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NBCC.NS", "description": "NBCC (India) Ltd", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "EIHOTEL.NS", "description": "EIH Ltd", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BAYERCROP.NS", "description": "Bayer Cropscience", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TATACHEM.NS", "description": "Tata Chemicals", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ABREAL.NS", "description": "Aditya Birla Real Estate", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NUVAMA.NS", "description": "Nuvama Wealth Management", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ASTRAZEN.NS", "description": "Astrazeneca Pharma India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HINDCOPPER.NS", "description": "Hindustan Copper", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "FIVESTAR.NS", "description": "Five-Star Business Finance", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INOXWIND.NS", "description": "Inox Wind", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RAMCOCEM.NS", "description": "The Ramco Cements", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "STARHEALTH.NS", "description": "Star Health & Allied Insurance", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HSCL.NS", "description": "Himadri Speciality Chemical", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NAVINFLUOR.NS", "description": "Navin Fluorine International", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ANGELONE.NS", "description": "Angel One", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KEC.NS", "description": "KEC International", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LALPATHLAB.NS", "description": "Dr Lal Pathlabs", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TIMKEN.NS", "description": "Timken India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CESC.NS", "description": "CESC Ltd", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "EMCUREPHARMA.NS", "description": "Emcure Pharmaceuticals", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SAGILITY.NS", "description": "Sagility India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CASTROLIND.NS", "description": "Castrol India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MANAPPURAM.NS", "description": "Manappuram Finance", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CARBORUNIV.NS", "description": "Carborundum Universal", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GRSE.NS", "description": "Garden Reach Shipbuilders & Engineers", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ERIS.NS", "description": "Eris Lifesciences", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BASF.NS", "description": "BASF India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BRAINBEES.NS", "description": "Brainbees Solutions", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SKFINDIA.NS", "description": "SKF India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DELHIVERY.NS", "description": "Delhivery", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "REDINGTON.NS", "description": "Redington", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "VEDANTFASH.NS", "description": "Vedant Fashions", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KANSAINER.NS", "description": "Kansai Nerolac Paints", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CAMS.NS", "description": "CAMS Services", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ADITYABIRLAAMC.NS", "description": "Aditya Birla Sun Life AMC", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AMARAJABAT.NS", "description": "Amara Raja Energy", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AADHARHOUSING.NS", "description": "Aadhar Housing Finance", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PFIZER.NS", "description": "Pfizer India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "APLLTD.NS", "description": "Alembic Pharmaceuticals", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SARDAEN.NS", "description": "Sarda Energy & Minerals", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ATUL.NS", "description": "Atul Ltd", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DEVYANI.NS", "description": "Devyani International", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TRITURBINE.NS", "description": "Triveni Turbine", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AFCONS.NS", "description": "Afcons Infrastructure", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CHALET.NS", "description": "Chalet Hotels", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KFINTECH.NS", "description": "KFin Technologies", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CONCORDBIO.NS", "description": "Concord Biotech", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DOMSINDUSTRIES.NS", "description": "Doms Industries", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JINDALSAW.NS", "description": "Jindal Saw", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RPOWER.NS", "description": "Reliance Power", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KARURVYSYA.NS", "description": "Karur Vysya Bank", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DCMSHRIRAM.NS", "description": "DCM Shriram", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ANANTRAJ.NS", "description": "Anant Raj", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IGL.NS", "description": "Indraprastha Gas Ltd (IGL)", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KALPATPOWR.NS", "description": "Kalpataru Projects", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BIKAJI.NS", "description": "Bikaji Foods International", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AAVAS.NS", "description": "AAVAS Financiers", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GSPL.NS", "description": "Gujarat State Petronet Ltd", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BLS.NS", "description": "BLS International", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TRIL.NS", "description": "T R I L", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SCHNEIDER.NS", "description": "Schneider Electric", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PCBL.NS", "description": "PCBL Chemical", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ZENSAR.NS", "description": "Zensar Technologies", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ANANDRATHI.NS", "description": "Anand Rathi Wealth", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SAILIFE.NS", "description": "Sai Life", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CENTURYPLY.NS", "description": "Century Plyboard", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BATAINDIA.NS", "description": "Bata India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JUPITER.NS", "description": "Jupiter Wagons", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IEX.NS", "description": "Indian Energy Exchange", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "VGUARD.NS", "description": "V-Guard Industries", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NEULANDLAB.NS", "description": "Neuland Labs", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SIGNATURE.NS", "description": "SignatureGlobal", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ELGIEQUIP.NS", "description": "Elgi Equipments", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CREDITACC.NS", "description": "Credit Access Grameen", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CAPLINPOINT.NS", "description": "Caplin Point Lab", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NAVA.NS", "description": "Nava", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ACE.NS", "description": "Action Construction Equipment", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "APTUS.NS", "description": "Aptus Value Housing", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IRCON.NS", "description": "Ircon International", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ASAHIINDIA.NS", "description": "Asahi India Glass", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BLUEDART.NS", "description": "Blue Dart Express", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GODREJAGRO.NS", "description": "Godrej Agrovet", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NATCOPHARM.NS", "description": "Natco Pharma", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JUBLPHARMA.NS", "description": "Jubilant Pharmova", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NIVABUPA.NS", "description": "Niva Bupa Health", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RAINBOW.NS", "description": "Rainbow Children's", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AARTIIND.NS", "description": "Aarti Industries", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NEWGEN.NS", "description": "Newgen Software", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DEEPAKFERT.NS", "description": "Deepak Fertilizers", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CYIENT.NS", "description": "Cyient", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CAPRIGLOBAL.NS", "description": "Capri Global", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RKFORGE.NS", "description": "Ramkrishna Forgings", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JBMA.NS", "description": "JBM Auto", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "FINCABLES.NS", "description": "Finolex Cables", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "EIDPARRY.NS", "description": "EID Parry", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IIFL.NS", "description": "IIFL Finance", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INDEGENE.NS", "description": "Indegene", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MGL.NS", "description": "Mahanagar Gas", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KAJARIACER.NS", "description": "Kajaria Ceramics", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ECLERX.NS", "description": "eClerx Services", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KIRLOSBROS.NS", "description": "Kirloskar Brothers", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GRAVITA.NS", "description": "Gravita India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "UTIAMC.NS", "description": "UTI AMC", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SWANENERGY.NS", "description": "Swan Energy", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BEML.NS", "description": "BEML Ltd", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TEJASNET.NS", "description": "Tejas Networks", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ZENTEC.NS", "description": "Zen Technologies", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GESHIP.NS", "description": "GE Shipping Co", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ALIVUS.NS", "description": "Alivus Life", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LTFOODS.NS", "description": "L T Foods", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NCC.NS", "description": "NCC", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "WELSPUNLIV.NS", "description": "Welspun Living", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HBLPOWER.NS", "description": "HBL Engineering", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SOBHA.NS", "description": "Sobha", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TBOTEK.NS", "description": "TBO Tek", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MINDACORP.NS", "description": "Minda Corp", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "WHIRLPOOL.NS", "description": "Whirlpool India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INDIAMART.NS", "description": "Indiamart Inter.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CLEAN.NS", "description": "Clean Science", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TRIDENT.NS", "description": "Trident", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BBTC.NS", "description": "Bombay Burmah", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JYOTHYLAB.NS", "description": "Jyothy Labs", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GPIL.NS", "description": "Godawari Power", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GRANULES.NS", "description": "Granules India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TECHNOE.NS", "description": "Techno Electric", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CEATLTD.NS", "description": "CEAT", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CUB.NS", "description": "City Union Bank", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CRAFTSMAN.NS", "description": "Craftsman Auto", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ACMESOL.NS", "description": "ACME Solar Holding", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "VTL.NS", "description": "Vardhman Textiles", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HFCL.NS", "description": "HFCL", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "IFCI.NS", "description": "IFCI", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "FINPIPE.NS", "description": "Finolex Industries", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BALRAMCHIN.NS", "description": "Balrampur Chini", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TATATEL.NS", "description": "Tata Tele. Mah.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "WESTLIFE.NS", "description": "Westlife Food", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "BSOFT.NS", "description": "Birlasoft Ltd", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RITES.NS", "description": "Rites", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TITAGARH.NS", "description": "Titagarh Rail", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RRKABEL.NS", "description": "R R Kabel", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RBLBANK.NS", "description": "RBL Bank", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RHIM.NS", "description": "RHI Magnesita", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KIRLOSENG.NS", "description": "Kirloskar Oil", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JUBLINGREA.NS", "description": "Jubilant Ingrev.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "VIJAYA.NS", "description": "Vijaya Diagnost.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "USHAMART.NS", "description": "Usha Martin", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PRAJIND.NS", "description": "Praj Industries", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LEMONTREE.NS", "description": "Lemon Tree Hotel", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JKBANK.NS", "description": "J & K Bank", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ELECON.NS", "description": "Elecon Engg. Co", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SAREGAMA.NS", "description": "Saregama India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NMDCSTEEL.NS", "description": "NMDC Steel", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JPPOWER.NS", "description": "JP Power Ven.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RAILTEL.NS", "description": "Railtel Corpn.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "QUESS.NS", "description": "Quess Corp", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SONATSOFTW.NS", "description": "Sonata Software", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INTELLECT.NS", "description": "Intellect Design", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "OLECTRA.NS", "description": "Olectra Greentec", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SBFC.NS", "description": "SBFC Finance", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "DATAPATTNS.NS", "description": "Data Pattern", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SAPPHIRE.NS", "description": "Sapphire Foods", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ZEEL.NS", "description": "Zee Entertainment", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RAYMOND.NS", "description": "Raymond", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GRAPHITE.NS", "description": "Graphite India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HEG.NS", "description": "HEG", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CEMAP.NS", "description": "C.E. Info System", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JMFINANCIL.NS", "description": "JM Financial", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CPCL.NS", "description": "C P C L", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MAHSEAMLES.NS", "description": "Maharashtra Seamless", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HOMEFIRST.NS", "description": "Home First Finance", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HAPPSTMNDS.NS", "description": "Happiest Minds", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INOXINDIA.NS", "description": "Inox India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ENGINERSIN.NS", "description": "Engineers India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PVRINOX.NS", "description": "PVR Inox", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CANFINHOME.NS", "description": "Can Fin Homes", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SAMMAAN.NS", "description": "Sammaan Capital", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "INDIACEM.NS", "description": "India Cements", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NETWEB.NS", "description": "Netweb Technologies", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GMDCLTD.NS", "description": "Gujarat Mineral Development Corporation", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TRIVENI.NS", "description": "Triveni Engineering", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ALKYLAMINE.NS", "description": "Alkyl Amines", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SYRMA.NS", "description": "Syrma SGS Technology", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "VALORESTATE.NS", "description": "Valor Estate", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "METROPOLIS.NS", "description": "Metropolis Healthcare", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MMTC.NS", "description": "MMTC Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SCI.NS", "description": "Shipping Corporation of India", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JKTYRE.NS", "description": "JK Tyre & Industries", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "LATENTVIEW.NS", "description": "Latent View Analytics", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "HONASA.NS", "description": "Honasa Consumer", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ALOKINDS.NS", "description": "Alok Industries", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "AKUMS.NS", "description": "Akums Drugs", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CCL.NS", "description": "CCL Products", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CERA.NS", "description": "Cera Sanitaryware", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GNFC.NS", "description": "Gujarat Narmada Valley Fertilizers & Chemicals", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "CAMPUS.NS", "description": "Campus Activewear", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "JUSTDIAL.NS", "description": "Just Dial", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RCF.NS", "description": "Rashtriya Chemicals & Fertilizers", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "MASTEK.NS", "description": "Mastek Ltd.", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "NETWORK18.NS", "description": "Network18 Media", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "GPPL.NS", "description": "Gujarat Pipavav Port", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "PNCINFRA.NS", "description": "PNC Infratech", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "KNRCON.NS", "description": "KNR Constructions", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RAYMONDL.NS", "description": "Raymond Lifestyle", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "TANLA.NS", "description": "Tanla Platforms", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "ROUTE.NS", "description": "Route Mobile", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "SHRENKA.NS", "description": "Shree Renuka Sugars", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "STERLINGW.NS", "description": "Sterling & Wilson", "market": "NSE", "type": "stock" },
  { "icon": "🌐", "name": "RATTANINDIA.NS", "description": "RattanIndia Enterprises", "market": "NSE", "type": "stock" },

  // Indices

  { "icon": "📊", "name": "^SPX", "description": "S&P 500 INDEX", "market": "Chicago Options", "type": "index" },
  { "icon": "📊", "name": "^NDX", "description": "NASDAQ 100", "market": "Nasdaq GIDS", "type": "index" },
  { "icon": "📊", "name": "^DJI", "description": "Dow Jones Industrial Average", "market": "DJI", "type": "index" },
  { "icon": "📊", "name": "^IXIC", "description": "NASDAQ Composite", "market": "Nasdaq GIDS", "type": "index" },
  { "icon": "📊", "name": "^NSEI", "description": "NIFTY 50", "market": "NSE", "type": "index" },
  { "icon": "📊", "name": "^CNX100", "description": "NIFTY 100", "market": "NSE", "type": "index" },
  { "icon": "📊", "name": "^NSEBANK", "description": "NIFTY BANK", "market": "NSE", "type": "index" },
  { "icon": "📊", "name": "^CNXFMCG", "description": "NIFTY FMCG", "market": "NSE", "type": "index" },
  { "icon": "📊", "name": "^CNXIT", "description": "NIFTY IT", "market": "NSE", "type": "index" },
  { "icon": "📊", "name": "^CNXAUTO", "description": "NIFTY AUTO", "market": "NSE", "type": "index" },
  { "icon": "📊", "name": "^CNXPHARMA", "description": "NIFTY PHARMA", "market": "NSE", "type": "index" },
  { "icon": "📊", "name": "^CNXENERGY", "description": "NIFTY ENERGY", "market": "NSE", "type": "index" },
  { "icon": "📊", "name": "^CNXREALTY", "description": "NIFTY REALTY", "market": "NSE", "type": "index" },
  { "icon": "📊", "name": "^CNXMETAL", "description": "NIFTY METAL", "market": "NSE", "type": "index" },
  { "icon": "📊", "name": "^CNXSERVICE", "description": "NIFTY SERVICES SECTOR", "market": "NSE", "type": "index" },
  { "icon": "📊", "name": "BSE-500.BO", "description": "S&P BSE 500 INDEX", "market": "BSE", "type": "index" },
  { "icon": "📊", "name": "BSE-OILGAS.BO", "description": "S&P BSE OIL&GAS INDEX", "market": "BSE", "type": "index" },
  { "icon": "📊", "name": "BSE-POWER.BO", "description": "S&P BSE POWER INDEX", "market": "BSE", "type": "index" },
  { "icon": "📊", "name": "BSE-TECK.BO", "description": "S&P BSE TECK INDEX", "market": "BSE", "type": "index" },
  { "icon": "📊", "name": "BSE-METAL.BO", "description": "S&P BSE METAL INDEX", "market": "BSE", "type": "index" },
  { "icon": "📊", "name": "BSE-REALTY.BO", "description": "S&P BSE REALTY INDEX", "market": "BSE", "type": "index" },
  { "icon": "📊", "name": "^FTSE", "description": "FTSE 100 INDEX", "market": "LSE", "type": "index" },
  { "icon": "📊", "name": "^DAX", "description": "DAX PERFORMANCE INDEX", "market": "Xetra", "type": "index" },
  { "icon": "📊", "name": "^CAC", "description": "CAC 40 INDEX", "market": "Euronext Paris", "type": "index" },
  { "icon": "📊", "name": "^N225", "description": "Nikkei 225", "market": "Tokyo Stock Exchange", "type": "index" },
  { "icon": "📊", "name": "^HSI", "description": "HANG SENG INDEX", "market": "Hong Kong Stock Exchange", "type": "index" },
  { "icon": "📊", "name": "^ASX", "description": "S&P/ASX 200", "market": "ASX", "type": "index" },
  { "icon": "📊", "name": "^STI", "description": "Straits Times Index", "market": "SGX", "type": "index" },
  { "icon": "📊", "name": "^KS11", "description": "KOSPI Composite Index", "market": "Korea Exchange", "type": "index" },
  { "icon": "📊", "name": "^BVSP", "description": "Bovespa Index", "market": "B3 - Brazil", "type": "index" },
  { "icon": "📊", "name": "^MXX", "description": "IPC Mexico", "market": "BMV - Mexico", "type": "index" },
  { "icon": "📊", "name": "^MOEX", "description": "MOEX Russia Index", "market": "Moscow Exchange", "type": "index" },
  { "icon": "📊", "name": "^TA125", "description": "TA-125 Index", "market": "TASE - Israel", "type": "index" },
  { "icon": "📊", "name": "^JTOPI", "description": "JSE All Share Index", "market": "JSE - South Africa", "type": "index" },
  { "icon": "📊", "name": "^NZ50", "description": "NZX 50 Index", "market": "NZX - New Zealand", "type": "index" },
  { "icon": "📊", "name": "^PSEI", "description": "PSEi Composite", "market": "PSE - Philippines", "type": "index" },



  // Cryptocurrencies
  { "icon": "💰", "name": "BTC-USD", "description": "Bitcoin USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "ETH-USD", "description": "Ethereum USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "BNB-USD", "description": "BNB USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "ADA-USD", "description": "Cardano USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "DOGE-USD", "description": "Dogecoin USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "XRP-USD", "description": "XRP USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "LTC-USD", "description": "Litecoin USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "SOL1-USD", "description": "Solana USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "DOT1-USD", "description": "Polkadot USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "UNI3-USD", "description": "Uniswap USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "LINK-USD", "description": "Chainlink USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "MATIC-USD", "description": "Polygon USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "AVAX-USD", "description": "Avalanche USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "XLM-USD", "description": "Stellar USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "ATOM-USD", "description": "Cosmos USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "ICP-USD", "description": "Internet Computer USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "FTM-USD", "description": "Fantom USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "FIL-USD", "description": "Filecoin USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "NEAR-USD", "description": "Near Protocol USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "VET-USD", "description": "VeChain USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "HNT-USD", "description": "Helium USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "AAVE-USD", "description": "Aave USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "GRT-USD", "description": "The Graph USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "EOS-USD", "description": "EOS USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "SAND-USD", "description": "The Sandbox USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "MANA-USD", "description": "Decentraland USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "THETA-USD", "description": "Theta Network USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "ENJ-USD", "description": "Enjin Coin USD", "market": "CCC", "type": "crypto" },
  { "icon": "💰", "name": "ZIL-USD", "description": "Zilliqa USD", "market": "CCC", "type": "crypto" },

  // Futures
  { "icon": "🔮", "name": "GC=F", "description": "Gold Apr 25", "market": "COMEX", "type": "futures" },
  { "icon": "🔮", "name": "SI=F", "description": "Silver May 25", "market": "COMEX", "type": "futures" },
  { "icon": "🔮", "name": "MHG=F", "description": "Micro Copper Futures, May 2025", "market": "COMEX", "type": "futures" },
  { "icon": "🔮", "name": "QM=F", "description": "E-mini Crude Oil Futures, Apr 2025", "market": "NY Mercantile", "type": "futures" },
  { "icon": "🔮", "name": "NQ=F", "description": "Nasdaq 100 Mar 25", "market": "CME", "type": "futures" },
  { "icon": "🔮", "name": "ES=F", "description": "E-Mini S&P 500 Mar 25", "market": "CME", "type": "futures" },
  { "icon": "🔮", "name": "YM=F", "description": "Mini Dow Jones Indus.-$5 Mar 25", "market": "CBOT", "type": "futures" },
  { "icon": "🔮", "name": "RTY=F", "description": "E-mini Russell 2000 Index Future", "market": "CME", "type": "futures" },
  { "icon": "🔮", "name": "CL=F", "description": "Crude Oil Apr 25", "market": "NY Mercantile", "type": "futures" },
  { "icon": "🔮", "name": "NG=F", "description": "Natural Gas Apr 25", "market": "NY Mercantile", "type": "futures" },
  { "icon": "🔮", "name": "HG=F", "description": "Copper May 25", "market": "COMEX", "type": "futures" },
  { "icon": "🔮", "name": "ZC=F", "description": "Corn Futures May 25", "market": "CBOT", "type": "futures" },
  { "icon": "🔮", "name": "ZW=F", "description": "Wheat Futures May 25", "market": "CBOT", "type": "futures" },
  { "icon": "🔮", "name": "ZS=F", "description": "Soybean Futures May 25", "market": "CBOT", "type": "futures" },
  { "icon": "🔮", "name": "LE=F", "description": "Live Cattle Futures Apr 25", "market": "CME", "type": "futures" },
  { "icon": "🔮", "name": "HE=F", "description": "Lean Hogs Futures Apr 25", "market": "CME", "type": "futures" },
  { "icon": "🔮", "name": "CC=F", "description": "Cocoa Futures May 25", "market": "ICE", "type": "futures" },
  { "icon": "🔮", "name": "KC=F", "description": "Coffee Futures May 25", "market": "ICE", "type": "futures" },
  { "icon": "🔮", "name": "CT=F", "description": "Cotton Futures May 25", "market": "ICE", "type": "futures" },
  { "icon": "🔮", "name": "LB=F", "description": "Lumber Futures May 25", "market": "CME", "type": "futures" },

  // Forex
  { "icon": "💱", "name": "EURUSD=X", "description": "EUR/USD", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "GBPUSD=X", "description": "GBP/USD", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "USDJPY=X", "description": "USD/JPY", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "AUDUSD=X", "description": "AUD/USD", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "USDCAD=X", "description": "USD/CAD", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "USDINR=X", "description": "USD/INR", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "USDZAR=X", "description": "USD/ZAR", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "USDCNY=X", "description": "USD/CNY", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "USDHKD=X", "description": "USD/HKD", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "USDCHF=X", "description": "USD/CHF", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "USDSEK=X", "description": "USD/SEK", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "USDSGD=X", "description": "USD/SGD", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "USDTHB=X", "description": "USD/THB", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "EURGBP=X", "description": "EUR/GBP", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "EURAUD=X", "description": "EUR/AUD", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "EURCAD=X", "description": "EUR/CAD", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "EURCHF=X", "description": "EUR/CHF", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "EURJPY=X", "description": "EUR/JPY", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "GBPJPY=X", "description": "GBP/JPY", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "AUDJPY=X", "description": "AUD/JPY", "market": "CCY", "type": "forex" },
  { "icon": "💱", "name": "CADJPY=X", "description": "CAD/JPY", "market": "CCY", "type": "forex" },

  // ETFs
  { "icon": "📈", "name": "VT", "description": "Vanguard Total World Stock ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "VTI", "description": "Vanguard Total Stock Market ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "VOO", "description": "Vanguard S&P 500 ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "IVV", "description": "iShares Core S&P 500 ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "SCHB", "description": "Schwab U.S. Broad Market ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "ARKK", "description": "ARK Innovation ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "VYM", "description": "Vanguard High Dividend Yield ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "JEPI", "description": "JPMorgan Equity Premium Income ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "TLT", "description": "iShares 20+ Year Treasury Bond ETF", "market": "NasdaqGM", "type": "etf" },
  { "icon": "📈", "name": "GLD", "description": "SPDR Gold Shares ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "SLV", "description": "iShares Silver Trust ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "EEM", "description": "iShares MSCI Emerging Markets ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "FXI", "description": "iShares China Large-Cap ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "VWO", "description": "Vanguard FTSE Emerging Markets ETF", "market": "NYSEArca", "type": "etf" },
  { "icon": "📈", "name": "QQQM", "description": "Invesco NASDAQ 100 ETF", "market": "NYSEArca", "type": "etf" }
];

export default symbols;